### ISSUE TITLE
AttributeError: module 'PIL' has no attribute 'PngImagePlugin' when running Gemini model on Windows 11

### ISSUE THREAD

**Issue by DHerls** [google-gemini/generative-ai-python#178]
### Description of the bug:

When attempting to run sample gemini text + image code on Windows, I receive the following error:

```
Traceback (most recent call last):
  File "C:\Users\dan\Projects\gemini_bug_report\without_import.py", line 10, in <module>
    response = model.generate_content(["Is the following image white?", image], stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\generative_models.py", line 234, in generate_content
    request = self._prepare_request(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\generative_models.py", line 204, in _prepare_request
    contents = content_types.to_contents(contents)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 239, in to_contents
    contents = [to_content(contents)]
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 202, in to_content
    return glm.Content(parts=[to_part(part) for part in content])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 202, in <listcomp>
    return glm.Content(parts=[to_part(part) for part in content])
                              ^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 172, in to_part
    return glm.Part(inline_data=to_blob(part))
                                ^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 135, in to_blob
    return image_to_blob(blob)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 63, in image_to_blob
    return pil_to_blob(image)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dan\.virtualenvs\gemini_bug_report-gfzPZTWW\Lib\site-packages\google\generativeai\types\content_types.py", line 49, in pil_to_blob
    if isinstance(img, PIL.PngImagePlugin.PngImageFile):
                       ^^^^^^^^^^^^^^^^^^
AttributeError: module 'PIL' has no attribute 'PngImagePlugin'
```

Versions:
```
Windows 11
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32

google-generativeai==0.3.2
pillow==10.2.0
```

I believe this is a problem in how this library is referencing `PngImagePlugin`

See reproduction here: https://github.com/DHerls/google_genai_import_bug_repro

File `without_import.py` causes the issue for me and `with_import.py` runs as expected.

### Actual vs expected behavior:

Actual behavior: `AttributeError: module 'PIL' has no attribute 'PngImagePlugin'`
Expected behavior: Code runs

## Proposed solution

Change code that references PngImagePlugin like this:

```python
import PIL
...
PIL.PngImagePlugin
```

to code that references PngImagePlugin like this:

```python
from PIL import PngImagePlugin
...
PngImportPlugin
```

**Comment by ymodak** [comment]
Hi @DHerls,  I tried your code snippets in google colab and both versions seem to work.
See [colab gist](https://colab.sandbox.google.com/gist/ymodak/06a0adff1ef7116f1942a1124647fa2b/untitled51.ipynb) Thanks!

**Comment by DHerls** [comment]
Hi @ymodak this only appears on Windows. Does Google Collab have a Windows runtime option?

**Comment by SpamMusubi153** [comment]
I had this same problem on Windows while using **Python 3.11** installed from the Microsoft Store. Importing the PngImagePlugin explicitly from PIL was also able to resolve the problem.

**Comment by MarkDaoust** [comment]
Sorry I missed this one. 

Thanks for fixing @mbanani!
