### ISSUE TITLE
Unable to call aivoke with transport="rest".

### ISSUE THREAD

**Issue by kento996** [google-gemini/generative-ai-python#268]
### Description of the bug:

When I set transport="rest" in ChatGoogleGenerativeAI, I can't use chain.ainvoke
```
def get_gemini_pro() -> BaseChatModel:

    return ChatGoogleGenerativeAI(model="gemini-1.5-pro-latest",
                                  temperature=0,
                                  convert_system_message_to_human=True,
                                  transport="rest")
async def invokeChain(code):
    llm=get_gemini_pro()
    chain=descriptionGenTemplate()|llm|CodeoutputStruction()
    res= await chain.ainvoke({"code":code})
    print(res)
if __name__ == '__main__':

    code="""
xxxxxxxxxxxxxxx
"""
    asyncio.run(invokeChain(code))
 ```
Executing the above code displays the following error:
```
Traceback (most recent call last):
  File "f:\code\pythonProject\Gemini_CWEs\codeExpansion.py", line 93, in <module>
    asyncio.run(invokeChain(code))
  File "E:\anaconda\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

                               ......

  File "C:\Users\kento\AppData\Local\pypoetry\Cache\virtualenvs\gemini-cwes-rly_BX-h-py3.11\Lib\site-packages\google\api_core\grpc_helpers_async.py", line 187, in error_remapped_callable
    raise TypeError("Unexpected type of call %s" % type(call))
TypeError: Unexpected type of call <class 'google.ai.generativelanguage_v1beta.types.generative_service.GenerateContentResponse'>
```

**Comment by MarkDaoust** [comment]
This might be streaming with `transport="rest"`  is broken.

**Comment by MarkDaoust** [comment]
No, It couldn't be that, since our streaming example works in colab and colab uses rest transport by default.

**Comment by MarkDaoust** [comment]
https://github.com/search?q=repo%3Agoogle-gemini%2Fgenerative-ai-python+%22Unexpected+type+of+call%22&type=issues
