### ISSUE TITLE
File uploads are broken (ValueError: Unknown field for File: state)

### ISSUE THREAD

**Issue by xarcnovn** [google-gemini/generative-ai-python#324]
### Description of the bug:

This looks similar to this https://github.com/google-gemini/generative-ai-python/issues/292

I used File API to upload images to Gemini and everything was working fine, but now File API returns ValueError: Unknown field for File: state. I did a simple test:

```
"import google.generativeai as genai

def test():
    genai.upload_file(path='video_screenshot1.png')

test()"
```

and it returns

```
"(.venv) karol@Karols-MacBook-Air src % /Users/karol/Desktop/projects/what_to_wear/src/.venv/bin/python /Users/karol/Desktop/projects/what_to_wear/src/test.py
Traceback (most recent call last):
  File "/Users/karol/Desktop/projects/what_to_wear/src/test.py", line 7, in <module>
    test()
  File "/Users/karol/Desktop/projects/what_to_wear/src/test.py", line 5, in test
    genai.upload_file(path='video_screenshot1.png')
  File "/Users/karol/Desktop/projects/what_to_wear/src/.venv/lib/python3.12/site-packages/google/generativeai/files.py", line 52, in upload_file
    response = client.create_file(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/karol/Desktop/projects/what_to_wear/src/.venv/lib/python3.12/site-packages/google/generativeai/client.py", line 76, in create_file
    return glm.File(
           ^^^^^^^^^
  File "/Users/karol/Desktop/projects/what_to_wear/src/.venv/lib/python3.12/site-packages/proto/message.py", line 576, in __init__
    raise ValueError(
ValueError: Unknown field for File: state"
```

Please help because it renders my Google AI hackathon project useless (and probably all projects using the upload_file method).

**Comment by mingsheu** [comment]
@xarcnovn can you confirm the version you are using?

pip
```console
$ pip show google.generativeai
Name: google-generativeai
Version: 0.5.2
Summary: Google Generative AI High level API client library and tools.
```

python
```python
print(genai.__version__)
```

I was able to replicate the exact error on 0.5.1 but not on 0.5.2 as expected.

**Comment by xarcnovn** [comment]
I was using the 0.5.1 version. I upgraded to 0.5.2 and it works now. However, it was working a few days ago with v0.5.1 too, I was using it extensively and had never stumbled upon this particular issue. I'm closing the issue then.
