### ISSUE TITLE
Unknown field for Candidate: finish_message

### ISSUE THREAD

**Issue by gabrielmdesidera** [google-gemini/generative-ai-python#559]
### Description of the bug:

During regular use, some requests to Gemini are returning this error instead of the response (Python project running in Docker):
```
chat-app-1  | 2024-09-17 14:34:44.282 Uncaught app exception
chat-app-1  | Traceback (most recent call last):
chat-app-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
chat-app-1  |     result = func()
chat-app-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
chat-app-1  |     exec(code, module.__dict__)
chat-app-1  |   File "/app/chat.py", line 135, in <module>
chat-app-1  |     if item.text:
chat-app-1  |   File "/usr/local/lib/python3.10/site-packages/google/generativeai/types/generation_types.py", line 454, in text
chat-app-1  |     if candidate.finish_message:
chat-app-1  |   File "/usr/local/lib/python3.10/site-packages/proto/message.py", line 906, in __getattr__
chat-app-1  |     raise AttributeError(
chat-app-1  | AttributeError: Unknown field for Candidate: finish_message
```

### Actual vs expected behavior:

By reading the code from [#527](https://github.com/google-gemini/generative-ai-python/pull/527/files), I assume the expected behaviour would be to raise another error with the intended message

**Comment by gabrielmdesidera** [comment]
This is the partial response that was returned that triggered this bug:

```
GenerateContentResponse(
    done=True,
    iterator=None,
    result=protos.GenerateContentResponse({
      "candidates": [
        {
          "finish_reason": "SAFETY",
          "index": 0,
          "safety_ratings": [
            {
              "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
              "probability": "NEGLIGIBLE"
            },
            {
              "category": "HARM_CATEGORY_HATE_SPEECH",
              "probability": "NEGLIGIBLE"
            },
            {
              "category": "HARM_CATEGORY_HARASSMENT",
              "probability": "NEGLIGIBLE"
            },
            {
              "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
              "probability": "HIGH"
            }
          ]
        }
      ],
      "usage_metadata": {
        "prompt_token_count": 121385,
        "candidates_token_count": 1,
        "total_token_count": 121386
      }
    }),
)
```


It looks like the safety violation should have triggered an error with a finish message, but the finish_message attribute is not present in the candidate instance, thus leading to the `AttributeError: Unknown field for Candidate: finish_message` bug

**Comment by Majid-cloud** [comment]
I faced the similar issue. Turns out that I was giving a prompt which was triggering a safety mechanism in the Gemini model. You have observed "finish_reason": "SAFETY" in response, indicating that the content generation was blocked due to safety concerns.  

can you try simple prompt and send request again.

**Comment by tianhuih** [comment]
Hi @gabrielmdesidera, I'm encountering the same error. May I know how you get partial response when an exception occurs?

**Comment by lingxiao216** [comment]
Hi, i have the same issue, and i tried to add this parameters in my code : 

```
safety_settings={
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE
            }   
```
            
I always got the same error.

**Comment by MarkDaoust** [comment]
https://github.com/google-gemini/generative-ai-python/pull/571
