### ISSUE TITLE
module 'google.generativeai' has no attribute 'ImageGenerationModel' for Image Generating

### ISSUE THREAD

**Issue by mimonirbd** [google-gemini/generative-ai-python#597]
### Description of the bug:

I am using this script for gemini api to generate image:
```
import os
import google.generativeai as genai

genai.configure(api_key=os.environ['GEMINI_API_KEY'])


model  = genai.ImageGenerationModel("imagen-3.0-generate-001")

result = model.generate_images(
    prompt="Fuzzy bunnies in my kitchen",
    number_of_images=2,
    safety_filter_level="block_only_high",
    person_generation="allow_adult",
    aspect_ratio="3:4",
    negative_prompt="Outside",
)

for image in result.images:
  print(image)

# The output should look similar to this:
# <vertexai.preview.vision_models.GeneratedImage object at 0x78f3396ef370>
# <vertexai.preview.vision_models.GeneratedImage object at 0x78f3396ef700>
# <vertexai.preview.vision_models.GeneratedImage object at 0x78f33953c2b0>
# <vertexai.preview.vision_models.GeneratedImage object at 0x78f33953c280>

for image in result.images:
  # Open and display the image using your local operating system.
  image._pil_image.show()
```
  

### Actual vs expected behavior:

I am using python 3.10 but when I run the code then showig this error: 
```
PS C:\Users\M i Monir\Documents\python project\gemini content writer> & "C:/Users/M i Monir/AppData/Local/Programs/Python/Python310/python.exe" "c:/Users/M i Monir/Documents/python project/gemini content writer/gemini image generator.py"
Traceback (most recent call last):
  File "c:\Users\M i Monir\Documents\python project\gemini content writer\gemini image generator.py", line 7, in <module>
    model  = genai.ImageGenerationModel("imagen-3.0-generate-001")
AttributeError: module 'google.generativeai' has no attribute 'ImageGenerationModel'
PS C:\Users\M i Monir\Documents\python project\gemini content writer> 
```

How to fix it

**Comment by Hamza-nabil** [comment]
The code is from [Generate images using Imagen 3 ](https://ai.google.dev/gemini-api/docs/imagen), but I think it not accurate as the current api SDK does not support image generation.

I found similar example in [this notebook](https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/vision/getting-started/image_generation.ipynb)  that use `ImageGenerationModel`  from `vertexai.preview.vision_models`  . it does make sense as the  output is `vertexai.preview.vision_models.GeneratedImage` object.

**Comment by mimonirbd** [comment]
That means currently it isn't possible to generate image by gemini api without vertext ai api?

**Comment by Gunand3043** [comment]
@mimonirbd , The model is still in early access and not generally available yet.

`Preview: Imagen 3 in the Gemini API is available as an early access release in private preview. It's not yet generally available.`

**Comment by mimonirbd** [comment]
@Gunand3043 Got it, Thanks.

**Comment by MarianoMolina** [comment]
Its kinda silly that the docs are nonsense. The code example throws an exception, and the API Docs make the claim that img models are usable, yet it seems they are not. 

I tried:

from google.generativeai.vision_models import ImageGenerationModel

Got this error too:
File "/usr/local/lib/python3.10/site-packages/google/generativeai/vision_models/_vision_models.py", line 695, in <module>
    class GenerateVideoOperation(operations.BaseOperation):
AttributeError: module 'google.generativeai.operations' has no attribute 'BaseOperation'. Did you mean: 'get_operation'?

The docs have been like this for weeks btw, so not sure what was the plan with this.

**Comment by Gunand3043** [comment]
Hi @MarianoMolina, Imagen 3 in the Gemini API is not publicly available yet. Stay tuned for announcements regarding the status of this feature. 

https://ai.google.dev/gemini-api/docs/imagen

**Comment by MarkDaoust** [comment]
Hi everyone, @Gunand3043 is correct, Imagen is currently in an EAP. 

The code supporting it is in the `imagen` branch, but if you're not part of the EAP you won;'t be able to access it. 

In the future we'll be more careful about exposing docs before things are generally available.

**Comment by bnicholl** [comment]
Any update as to when this will be available to the public?

**Comment by nbkhope** [comment]
Bump

**Comment by Shah-Afraz411** [comment]
I tried this:
imagen = genai.models.ImageGenerationModel("imagen-3.0-generate-001")

It does not give any error but, I get this in result
  File "/home/runner/workspace/Model.py", line 10, in <module>
    imagen = genai.models.ImageGenerationModel("imagen-3.0-generate-001")

**Comment by Giom-V** [comment]
Imagen is still not available publicly, which is why you're getting an error.

**Comment by Giom-V** [comment]
We don't have dates as we prefer to iterate on the models until everyone is satisfied with it. But I'd be surprised if it was taking more than a few weeks.

**Comment by germangetgloby** [comment]
I've spent an entire day going in circles due to implementation errors with this. The public documentation is essentially the only source of truth - fix that

**Comment by bnicholl** [comment]
On this page

https://ai.google.dev/gemini-api/docs/imagen

it does ay

> Preview: Imagen 3 is available as an early access release in private preview. It's not yet generally available in the API.

Would be nice if there was some sort of timeline where we can expect this to be available to the general public though

**Comment by bnicholl** [comment]
Can we get some type of ETA on when the API will be available to the public? Or should I just assume it won't be available this year and focus on using openAI or bedrock?

**Comment by DesmondChoy** [comment]
I'm able to use `imagen-3.0-generate-002` with the API, but using `imagen-3.0-fast-generate-001` gives me this error: 
```
{'error': {'code': 404, 'message': 'models/imagen-3.0-fast-generate-001 is not found for API version v1beta, or is not supported for predict. Call ListModels to see the list of available models and their supported methods.', 'status': 'NOT_FOUND'}}
```

Class used to call imagen 3.0 v2:

```
from google import genai
from google.genai.types import GenerateImagesConfig
from PIL import Image
from io import BytesIO
import base64
import os
import asyncio

class ImageGenerationService:
    """Service for generating images from text prompts using Gemini's Imagen API."""

    def __init__(self):
        """Initialize Gemini service with the specified model."""
        self.model_name = "imagen-3.0-generate-002"
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key:
            logger.warning("GOOGLE_API_KEY is not set in environment variables!")

        # Create a client with the API key
        self.client = genai.Client(api_key=api_key)

    async def generate_image_async(self, prompt, retries=5):
        """Generate image asynchronously and return as base64 string.

        Args:
            prompt: Text description of the image to generate
            retries: Number of retry attempts if generation fails

        Returns:
            Base64 encoded string of the generated image, or None if generation fails
        """
        try:
            # Run in a thread pool to avoid blocking
            loop = asyncio.get_event_loop()
            return await loop.run_in_executor(
                None, self._generate_image, prompt, retries
            )
        except Exception as e:
            logger.error(f"Image generation failed: {str(e)}")
            return None

    def _generate_image(self, prompt, retries=5):
        """Internal method to call Gemini API.

        Args:
            prompt: Text description of the image to generate
            retries: Number of retry attempts if generation fails

        Returns:
            Base64 encoded string of the generated image, or None if generation fails
        """
        attempt = 0
        while attempt <= retries:
            try:
                logger.info(f"Generating image for prompt: {prompt}")
                logger.debug("\n=== DEBUG: Image Generation Request ===")
                logger.debug(f"Prompt: {prompt}")
                logger.debug(f"Model: {self.model_name}")
                logger.debug("========================\n")

                # Generate image using the client's models interface
                response = self.client.models.generate_images(
                    model=self.model_name,
                    prompt=prompt,
                    config=GenerateImagesConfig(number_of_images=1),
                )

                # Log response structure for debugging
                logger.debug("\n=== DEBUG: Image Generation Response ===")
                logger.debug(f"Response type: {type(response)}")
                # logger.debug(f"Response attributes: {dir(response)}")
                if (
                    hasattr(response, "generated_images")
                    and response.generated_images is not None
                ):
                    logger.debug(
                        f"Generated images count: {len(response.generated_images)}"
                    )
                    if response.generated_images:
                        logger.debug(
                            f"First image type: {type(response.generated_images[0])}"
                        )
                        # logger.debug(
                        #     f"First image attributes: {dir(response.generated_images[0])}"
                        # )
                else:
                    logger.debug("No generated_images attribute or it is None")
                logger.debug("========================\n")

                # Extract image data from response
                if response.generated_images:
                    # Convert to base64
                    image_bytes = response.generated_images[0].image.image_bytes
                    logger.debug(
                        f"Found image data with size: {len(image_bytes)} bytes"
                    )
                    image = Image.open(BytesIO(image_bytes))
                    buffered = BytesIO()
                    image.save(buffered, format="JPEG")
                    img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
                    logger.info(f"Successfully generated image for prompt: {prompt}")
                    return img_str
                logger.warning(f"No images generated for prompt: {prompt}")
                return None
            except Exception as e:
                logger.error(f"Image generation attempt {attempt + 1} failed: {str(e)}")
                attempt += 1
                if attempt <= retries:
                    # Wait before retry with exponential backoff
                    backoff_time = 2**attempt
                    logger.info(f"Retrying in {backoff_time} seconds...")
                    time.sleep(backoff_time)

        return None

```
